# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-25 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pokes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pokees', models.ManyToManyField(related_name='pokers', through='users_app.Poke', to='users_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='poke',
            name='poke_giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poke_givers', to='users_app.User'),
        ),
        migrations.AddField(
            model_name='poke',
            name='poke_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poke_receivers', to='users_app.User'),
        ),
    ]
