# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_auto_20170823_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='all_pokes',
            field=models.IntegerField(default=0),
        ),
    ]
