# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_user_all_pokes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_this_rel', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='pokes_given',
        ),
        migrations.AddField(
            model_name='pokes',
            name='poke_giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poke_givers', to='users_app.User'),
        ),
        migrations.AddField(
            model_name='pokes',
            name='poke_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poke_receivers', to='users_app.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='relationships',
            field=models.ManyToManyField(related_name='related_to', through='users_app.Pokes', to='users_app.User'),
        ),
    ]
